### ISSUE TITLE
Привет, че когда продолжение?

### ISSUE THREAD

**Issue by abobafett-dev** [Nertsal/quantum-dungeon#1]
Можно просто скипать ходы, если ты знаешь сколько тебе нужно на прохождение уровня и так фармить предметы...

Вроде бы ты уже знаешь про эти баги, но я все равно их напишу.

Можно быстро проскипать ход, пока происходит анимация смерти врага. Что дает возможность раньше выбрать следующий предмет.

Если пропускать ход нажимая на ячейку с игроком, игрок телепортируется на другую ячейку, при этом старая ячейка, с прошлого хода, лочиться.

Whoooops... No element at index. ... Вроде бы когда происходит анимация исчезания врага и при этом он же получает урон, но это не точно.

я не могу пройти дальше 5-10 уровня из-за последнего бага...

**Comment by Nertsal** [comment]
the bugs have been fixed
suppose we can close it now
